#!/usr/bin/env python3
"""One-shot prep: docx -> working directory.

    python scripts/prep.py file.docx -o work/
    -> work/unpacked/      the ONLY edit surface (lxml directly;
                           python-docx via opc.edit_docx)
    -> work/baseline.docx  read-only reference copy (the verify/diff
                           baseline) -- nobody edits it, by permission
    -> work/view.txt       baseline view

Prep instruments the working copy (both forms carry the SAME bytes):
- merges fragmented runs (Word save-noise splits phrases across <w:r>,
  making text unsearchable; merging changes run boundaries, which is
  why the baseline must be taken AFTER the merge -- diffing against the
  user's original would blame the merge noise on the edit);
- strips proofErr/rsid save noise;
- backfills + dedupes w14:paraId, so every paragraph has the stable
  #id the write tools target.

Merge rules stay conservative (a missed merge is harmless, a wrong
merge loses formatting): adjacent + structurally equal rPr + pure
text runs only.

For legacy .doc, convert first: soffice --headless --convert-to docx file.doc
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

from lxml import etree

sys.path.insert(0, str(Path(__file__).parent))
import opc  # noqa: E402  (shared OPC plumbing: safe unpack, atomic IO)
import walker  # noqa: E402  (the one rendered-text rule)

# Windows consoles/pipes default to the legacy ANSI code page (cp1252/cp936):
# the engine's CJK messages must never crash the gate there.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).parent
W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
XML_SPACE = "{http://www.w3.org/XML/1998/namespace}space"


# ---------------- fragmented-run merging ----------------

def _key(el):
    """Element -> structural key (tag + sorted attrs + recursive subtree), namespace-safe."""
    return (el.tag, tuple(sorted(el.attrib.items())),
            tuple(_key(c) for c in el))


def _rpr_key(run):
    rpr = run.find(W + "rPr")
    if rpr is None or len(rpr) == 0:
        return None
    return _key(rpr)


def _text_kind(run):
    """Run content all w:t -> 't'; all w:delText -> 'delText'; else None."""
    kinds = {c.tag for c in run if c.tag != W + "rPr"}
    if kinds == {W + "t"}:
        return "t"
    if kinds == {W + "delText"}:
        return "delText"
    return None                        # empty run or non-text children: skip


#: ONE rendered-text rule project-wide: walker.rendered owns the
#: xml:space trim (and the silent-layout-change scar history).
_rendered = walker.rendered


def _strip_noise(root) -> int:
    """Remove save noise: w:proofErr markers (empty spell-check flags that
    sit BETWEEN runs and block adjacency merging) and rsid* attributes on
    runs (revision-save ids; pure noise, regenerated by Word)."""
    n = 0
    for el in list(root.iter(W + "proofErr")):
        parent = el.getparent()
        if parent is not None:
            parent.remove(el)
            n += 1
    for r in root.iter(W + "r"):
        for k in list(r.attrib):
            if "rsid" in k.lower():
                del r.attrib[k]
                n += 1
    return n


def merge_part(root) -> int:
    """Merge adjacent same-format pure-text runs in place; -> number of runs merged away."""
    n = 0
    for parent in root.iter():
        kids = list(parent)
        i = 0
        while i < len(kids) - 1:
            a, b = kids[i], kids[i + 1]
            if not (a.tag == W + "r" and b.tag == W + "r"):
                i += 1
                continue
            ka, kb = _text_kind(a), _text_kind(b)
            if ka is None or ka != kb or _rpr_key(a) != _rpr_key(b) \
                    or (b.tail or "").strip() or (a.tail or "").strip():
                i += 1
                continue
            tag = W + ka
            text = "".join(_rendered(t) for t in a.iter(tag)) + \
                   "".join(_rendered(t) for t in b.iter(tag))
            for c in [c for c in a if c.tag == tag][1:]:
                a.remove(c)
            t0 = a.find(tag)
            t0.text = text
            if text != text.strip(" \t\n\r"):
                t0.set(XML_SPACE, "preserve")
            elif XML_SPACE in t0.attrib:
                del t0.attrib[XML_SPACE]
            a.tail = b.tail
            parent.remove(b)
            kids.pop(i + 1)
            n += 1                      # do not advance i: keep absorbing the next run
    return n


#: A .dotx package declares its main part as ...wordprocessingml.template
#: .main+xml. python-docx refuses to open that ("is not a Word file"), so
#: the working copy (baseline.docx / unpacked, which edit_docx feeds to
#: python-docx) has to be typed as a document, not a template. SKILL.md
#: once advertised .dotx support while the copy was unopenable (dxv2-6
#: review W2).
_TPL_CT = ("application/vnd.openxmlformats-officedocument."
           "wordprocessingml.template.main+xml")
_DOC_CT = ("application/vnd.openxmlformats-officedocument."
           "wordprocessingml.document.main+xml")


W14 = "http://schemas.microsoft.com/office/word/2010/wordml"
MC = "http://schemas.openxmlformats.org/markup-compatibility/2006"
#: comments.xml paraIds are RELATIONAL KEYS (commentsExtended references
#: them); rewriting one silently severs a thread. comment.py owns them.
_ID_SKIP = ("word/comments",)


def _bind_ns(root, prefix: str, uri: str):
    """Return a root whose nsmap binds `uri` (existing binding wins).
    lxml cannot add to an element's nsmap in place -- re-root when
    missing. -> (root, actual_prefix)."""
    for p, u in (root.nsmap or {}).items():
        if u == uri and p:
            return root, p
    nsmap = {p: u for p, u in (root.nsmap or {}).items()}
    nsmap[prefix] = uri
    if MC not in nsmap.values():
        nsmap["mc"] = MC
    new = etree.Element(root.tag, nsmap=nsmap)
    for k, v in root.attrib.items():
        new.set(k, v)
    new.text = root.text
    for c in list(root):
        new.append(c)
    return new, prefix


def _ensure_paraids(roots: dict) -> tuple:
    """Backfill + dedupe w14:paraId across story parts, so the view's
    #id is a total, unambiguous write-side coordinate (wild files from
    WPS/LO lack ids or carry copy-paste duplicates). First occurrence
    (sorted part name, doc order) keeps a duplicated id; later ones get
    fresh ones. Skips comments.xml (see _ID_SKIP) but counts its ids in
    the uniqueness pool. -> (n_assigned, set(changed part names))."""
    import revreg
    A = f"{{{W14}}}paraId"
    used: set = set()
    for name in sorted(roots):
        for p in roots[name][0].iter(W + "p"):
            v = p.get(A)
            if v:
                used.add(v.upper())

    def fresh(seed: str) -> str:
        v = revreg.fresh_pid(seed, used)   # THE one allocator
        used.add(v)
        return v

    n = 0
    changed: set = set()
    # ids in skipped parts pre-seed `seen`: a body paragraph that
    # happens to duplicate a comment paragraph's id gets rewritten
    # (body ids carry no relations; comment ids do)
    seen: set = set()
    for name in sorted(roots):
        if name.startswith(_ID_SKIP):
            for p in roots[name][0].iter(W + "p"):
                v = p.get(A)
                if v:
                    seen.add(v.upper())
    for name in sorted(roots):
        if name.startswith(_ID_SKIP):
            continue
        root, dirty = roots[name]
        # pass 1: full scan BEFORE any re-rooting -- re-rooting moves
        # children and would break the live iterator
        need = []
        for i, p in enumerate(root.iter(W + "p")):
            v = p.get(A)
            ok = (v and len(v) == 8 and v.upper() not in seen
                  and all(c in "0123456789abcdefABCDEF" for c in v)
                  and int(v, 16) < 0x80000000)
            if ok:
                seen.add(v.upper())
            else:
                need.append((i, p, v))
        if not need:
            continue
        if W14 not in (root.nsmap or {}).values():
            root, pref = _bind_ns(root, "w14", uri=W14)
            ig = root.get(f"{{{MC}}}Ignorable", "")
            if pref not in ig.split():
                root.set(f"{{{MC}}}Ignorable", (ig + " " + pref).strip())
            roots[name] = (root, dirty)
        # pass 2: the (i, p, v) element refs survived the re-root --
        # lxml append MOVES the same objects under the new root
        for i, p, v in need:
            nv = fresh(f"prep:{name}:{i}:{v or ''}")
            p.set(A, nv)
            seen.add(nv)
            n += 1
        changed.add(name)
    return n, changed


def merge_docx(src: Path, dst: Path) -> tuple:
    """src -> dst working baseline: merge fragmented runs, strip save
    noise, backfill/dedupe paraId, in every story-ish word/*.xml part.
    A template main part is retyped to a document one on the way out
    (the baseline is a WORKING COPY, not a redistribution of the
    template). -> (merge count, paraId backfill count)."""
    total = 0
    touched = {}
    roots: dict = {}
    import opc as _opc
    with _opc.CappedZip(src) as z:     # capped: zip-bomb defense
        try:
            ctb = z.read("[Content_Types].xml")
        except KeyError:
            ctb = b""
        if _TPL_CT.encode() in ctb:
            touched["[Content_Types].xml"] = ctb.replace(
                _TPL_CT.encode(), _DOC_CT.encode())
        for name in z.namelist():
            if not (name.startswith("word/") and name.endswith(".xml")):
                continue
            data = z.read(name)
            # <w:p too, not just <w:r: a part of empty paragraphs has
            # ids to backfill but no runs to merge
            if b"<w:r" not in data and b"<w:p " not in data \
                    and b"<w:p>" not in data:
                continue
            root = etree.fromstring(data)
            stripped = _strip_noise(root)
            k = merge_part(root)
            total += k
            roots[name] = (root, bool(k or stripped))
    n_ids, id_changed = _ensure_paraids(roots)
    for name, (root, dirty) in roots.items():
        if dirty or name in id_changed:
            touched[name] = etree.tostring(
                root, xml_declaration=True, encoding="UTF-8",
                standalone=True)
    opc.atomic_zip_rewrite(src, dst, touched)
    return total, n_ids


# ---------------- main flow ----------------

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("src", help=".docx input")
    ap.add_argument("-o", "--out", default="work", help="working directory")
    ap.add_argument("-f", "--force", action="store_true",
                    help="redo an already-prepared working dir "
                         "(overwrites unpacked/ edits!)")
    a = ap.parse_args()
    src, out = Path(a.src), Path(a.out)
    if src.suffix.lower() == ".doc":
        raise SystemExit("E_LEGACY_DOC: .doc is the pre-2007 binary "
                         "format | try: soffice --headless "
                         "--convert-to docx file.doc, then re-run")
    out.mkdir(parents=True, exist_ok=True)
    unpacked = out / "unpacked"
    baseline = out / "baseline.docx"
    view = out / "view.txt"

    # Re-run handling. Trajectory data: agents re-ran prep up to 5x on
    # one case -- the call is redundant, so make it HARMLESS, not fatal.
    # Three states, three answers:
    #   source unchanged + workspace untouched -> idempotent no-op exit;
    #   workspace edited / source changed      -> self-explaining refusal;
    #   -f                                     -> explicit rebuild.
    # Any existing unpacked/ stays protected even WITHOUT state.json:
    # step (2) rmtree()s it, and "state.json happens to be missing" must
    # never be the difference between a refusal and deleting files.
    if unpacked.exists():
        import json as _json
        st = None
        try:
            st = _json.loads((out / "state.json")
                             .read_text(encoding="utf-8"))
        except (OSError, ValueError):
            pass
        same_src = um = False
        if st and st.get("src_hash"):
            try:
                same_src = opc.file_hash(src) == st["src_hash"]
                um = opc.tree_hash(unpacked) == st.get("unpacked_hash")
            except OSError:
                pass
        if same_src and um and baseline.exists() and not a.force:
            if view.exists():
                print(f"workspace is up to date (neither the source file "
                      f"nor {out}/ changed); nothing was done. Use the "
                      f"existing {view}; pass -f to force a rebuild.")
                return 0
            # the view is a derivative: rebuild it without touching the workspace
            r = subprocess.run(
                [sys.executable, str(HERE / "read.py"), str(baseline)],
                capture_output=True, text=True,
                encoding="utf-8", errors="replace")
            if r.returncode:
                raise SystemExit("E_VIEW_RENDER: view rebuild failed | "
                                 + (r.stderr or r.stdout)[-300:])
            view.write_text(r.stdout, encoding="utf-8")
            print(f"workspace unchanged, only the view was missing — "
                  f"rebuilt {view} ({len(r.stdout):,} chars); "
                  f"nothing else touched.")
            return 0
        if not a.force:
            raise SystemExit(
                (f"E_WORKSPACE_EDITED: {unpacked} has edits; re-running "
                 f"prep would DISCARD them | current state: read.py "
                 f"{unpacked} (diff: read.py {baseline} --diff "
                 f"{unpacked}) | try: continue editing, no prep re-run "
                 "needed; -f rebuilds and discards ALL edits"
                 if same_src and not um else
                 f"E_WORKSPACE_EXISTS: {unpacked} exists and source or "
                 "workspace changed; re-running would lose its state | "
                 "try: -f to rebuild (discards ALL edits)"))

    # (1) merge fragmented runs + backfill/dedupe paraId
    #     (text becomes searchable, every paragraph gets a stable #id;
    #     rendering unchanged)
    if baseline.exists():
        baseline.chmod(0o644)            # -f rebuild over the 444 copy
    n_merged, n_ids = merge_docx(src, baseline)

    # (2) unpack -- foreign docx is untrusted; opc.unpack carries the
    #     hostile-entry defense (../, absolute paths, symlink entries)
    if unpacked.exists():
        shutil.rmtree(unpacked)
    opc.unpack(baseline, unpacked)
    # the baseline is a REFERENCE OBJECT, not an edit surface: read-only
    # by construction, so "don't overwrite the baseline" stops being a
    # discipline and becomes an impossible mistake
    baseline.chmod(0o444)

    # (3) baseline view
    r = subprocess.run([sys.executable, str(HERE / "read.py"),
                        str(baseline)], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode:
        raise SystemExit("E_VIEW_RENDER: view render failed | "
                         + (r.stderr or r.stdout)[-300:])
    view.write_text(r.stdout, encoding="utf-8")

    import json
    (out / "state.json").write_text(json.dumps(
        {"v": 3, "src": str(src), "unpacked": str(unpacked),
         "baseline": str(baseline), "view": str(view),
         # src_hash: lets a redundant re-run exit as a no-op instead of
         # refusing (agents re-ran prep 5x on one measured case).
         "src_hash": opc.file_hash(src),
         "unpacked_hash": opc.tree_hash(unpacked),
         "baseline_hash": opc.file_hash(baseline)}, ensure_ascii=False))
    print(f"merged {n_merged} fragmented runs; "
          f"paraId backfilled/dedup {n_ids}")
    print(f"unpacked = {unpacked}/   # the single working copy: edit "
          "directly with lxml, or via opc.edit_docx() for python-docx "
          "(see references/editing.md §0); raw XML of one block: "
          f"read.py {unpacked} --raw N")
    print(f"baseline = {baseline}   # read-only reference (acceptance "
          "baseline) — never edit it")
    print(f"view     = {view}   ({len(r.stdout):,} chars)  "
          "# body text + effective formatting + comments (@cmt) + revisions "
          "(«») are all here — do NOT parse comments.xml yourself; copy #id "
          "from block lines to locate edits; for a format audit read the "
          "view to EOF")
    print(f"finish: python scripts/opc.py pack {unpacked} out.docx && "
          f"python scripts/verify.py out.docx --baseline {baseline}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
